HUMAN_NAMES = {
    'master': 'master & 1 & pick',
    'ts': 'timestamp & {num} & pick',
    'depth': 'depth & {num} & pick',
    'size': 'size & {num} & pick',
    'author': 'author & {num} & pick',
    'ts_mours': 'timestamp & {num} & partial merge',
    'depth_mours': 'depth & {num} & partial merge',
    'size_mours': 'size & {num} & partial merge',
    'author_mours': 'author & {num} & partial merge',
    'ts_merge': 'timestamp & {num} & merged',
    'depth_merge': 'depth & {num} & merged',
    'size_merge': 'size & {num} & merged',
    'author_merge': 'author & {num} & merged',
    'topmost_random': 'random & 1 & pick',
    'random_merge': 'random & {num} & merged',
    'random_mours': 'random & {num} & partial merge',
}
